<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create New Account Please register  ent_1e29d0</name>
   <tag></tag>
   <elementGuidId>a5d122d1-e59e-400b-b394-04b55a23e320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.flex-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='register-banner']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>581d8931-ca81-4a83-be5e-9448f3232835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-column</value>
      <webElementGuid>b50707a0-88f5-4984-8e71-2f0253b8774c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Account Please register &amp; enter your details Full nameEmailPhone Number+62Date of BirthCreate PasswordConfirmation PasswordRefresh captcha Create account </value>
      <webElementGuid>596aeedf-b1e2-43eb-bc85-2d042345cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-banner&quot;)/div[@class=&quot;d-flex flex-column&quot;]</value>
      <webElementGuid>b4162037-54af-44eb-97fa-af8a5277fd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div</value>
      <webElementGuid>92c735b2-dbbe-4036-a61e-605db37f28df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>2e264ff0-bdb2-4149-a3e9-1ccfd6286c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create New Account Please register &amp; enter your details Full nameEmailPhone Number+62Date of BirthCreate PasswordConfirmation PasswordRefresh captcha Create account ' or . = 'Create New Account Please register &amp; enter your details Full nameEmailPhone Number+62Date of BirthCreate PasswordConfirmation PasswordRefresh captcha Create account ')]</value>
      <webElementGuid>9e6e1c89-549b-4162-a8d9-7cf44bc664c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
