<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Refresh captcha_captchaAnswer</name>
   <tag></tag>
   <elementGuidId>8fe5aa64-5dbe-47e5-9aa4-4c784af9a92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae46c8c4-55b8-469f-96d2-dc879f963b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>2594e438-60ea-426e-ac27-c1fab8ebd3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a9525ce-086c-4c86-8c05-a06b1ca20073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Captcha Above</value>
      <webElementGuid>6b7ad35d-1cff-4b3a-8045-7011f47da050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>bc5782c4-b92b-428f-bbbe-28104442e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ec-neutral-500 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>37f39643-8cb6-4e00-9100-8b934bc36ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaAnswer&quot;)</value>
      <webElementGuid>3a572483-f358-4a5a-ba5a-0327735e2449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaAnswer']</value>
      <webElementGuid>3a6e2393-9000-40fe-bb72-7269e96d3fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/div[3]/form/div[8]/div/div/input</value>
      <webElementGuid>c300835d-310c-456f-9d93-8dbb87150ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>05385c20-6e00-4dca-b38a-10f82e1235c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captchaAnswer' and @type = 'text' and @placeholder = 'Insert Captcha Above']</value>
      <webElementGuid>147e352e-4733-4c26-bc2f-e03ee2524e1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
