<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resent verification email</name>
   <tag></tag>
   <elementGuidId>39fe3025-b1e2-4bc2-8a61-ea33aa5f3b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ec-secondary-500.text-decoration-underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82bc79b4-8343-498a-981d-47357df794ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-secondary-500 text-decoration-underline</value>
      <webElementGuid>4d8e706b-7b7d-47c6-97fa-9b5c872fce98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Resent verification email</value>
      <webElementGuid>690e2893-8b33-420f-8216-ba2b9b515cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-banner&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;col-11 mx-auto&quot;]/div[@class=&quot;d-flex flex-md-row flex-column container mx-auto vh-100&quot;]/div[@class=&quot;col-12 col-md-4 justify-content-center right-side d-flex&quot;]/div[@class=&quot;ec-row py-5 ms-3&quot;]/div[@class=&quot;col-12 d-flex flex-column justify-content-center&quot;]/span[@class=&quot;text-activation fw-bold ec-primary-500&quot;]/span[@class=&quot;ec-secondary-500 text-decoration-underline&quot;]</value>
      <webElementGuid>4d16f6cc-9587-428b-a415-d0f7f0172df9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/span/span</value>
      <webElementGuid>754cbf10-ae40-47f5-b426-14c2d8c814a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Verification'])[1]/following::span[2]</value>
      <webElementGuid>5ab87846-8909-4cb8-a083-42c9f5853af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resent verification email']/parent::*</value>
      <webElementGuid>da05de00-9bde-48c2-9ec2-86f5c79fbae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>633f3ebd-e05d-494f-a800-5af19f204184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Resent verification email' or . = ' Resent verification email')]</value>
      <webElementGuid>702c1915-a614-496a-b43e-8f99ac2ccef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
