<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please verify your account to complete_a3c986</name>
   <tag></tag>
   <elementGuidId>c3d9ab7a-9b9f-4beb-b36c-9e30ae9dc881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-activation.fw-bold.ec-primary-500</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0fae796-0a70-4b5b-a4aa-1b55d356523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-activation fw-bold ec-primary-500</value>
      <webElementGuid>45be57c4-d5c7-4aaf-b712-8d244850aae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please verify your account to complete the registration process. Open the email and click the verification link. Didn’t get an email?  Resent verification email</value>
      <webElementGuid>f078cb03-d65a-48e6-9fa7-b2d59b4052ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-banner&quot;)/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;col-11 mx-auto&quot;]/div[@class=&quot;d-flex flex-md-row flex-column container mx-auto vh-100&quot;]/div[@class=&quot;col-12 col-md-4 justify-content-center right-side d-flex&quot;]/div[@class=&quot;ec-row py-5 ms-3&quot;]/div[@class=&quot;col-12 d-flex flex-column justify-content-center&quot;]/span[@class=&quot;text-activation fw-bold ec-primary-500&quot;]</value>
      <webElementGuid>f58adbc9-3f55-4e56-8422-009ec83f641c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>7c18bcb6-81c6-4e80-aa9d-fce7e619ea30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Verification'])[1]/following::span[1]</value>
      <webElementGuid>40df747a-4aa2-4314-a603-336e9bcaaf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please verify your account to complete the registration process. Open the email and click the verification link. Didn’t get an email?']/parent::*</value>
      <webElementGuid>e3959a36-46b7-4fd8-94dc-9061da78c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>21589895-3e6c-4518-b584-9b82726af911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Please verify your account to complete the registration process. Open the email and click the verification link. Didn’t get an email?  Resent verification email' or . = ' Please verify your account to complete the registration process. Open the email and click the verification link. Didn’t get an email?  Resent verification email')]</value>
      <webElementGuid>d34957d1-1d89-4af8-a46c-e2da8f800b98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
