<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Refresh captcha_captchaAnswer</name>
   <tag></tag>
   <elementGuidId>8dabba88-119d-497d-9ec0-11238050cf23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83b88bca-7766-43ab-904e-b40bfd8574c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>8f646cae-db3d-4e6a-a928-35c37d2cfb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>214dd654-5112-446e-98f5-87930c61db28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Captcha Above</value>
      <webElementGuid>952c8d0e-db76-4f10-b30f-812c8af86d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>74c24991-f1d8-4440-807a-4d880a80a4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ec-neutral-500 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>538ae3f8-edb3-47dc-b760-80c480710a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaAnswer&quot;)</value>
      <webElementGuid>700a80a5-9501-4608-9b79-49e6e1a24ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaAnswer']</value>
      <webElementGuid>19bf618c-b04d-45ab-a420-46c55945228f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/div[3]/form/div[8]/div/div/input</value>
      <webElementGuid>52e724f9-7b29-48a2-96e3-8d4c5edfd732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>8177275b-30e4-4540-ad1b-671672ac7dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captchaAnswer' and @type = 'text' and @placeholder = 'Insert Captcha Above']</value>
      <webElementGuid>bdb16f01-f498-420f-9013-deb50059edc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
