<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Refresh captcha_captchaAnswer</name>
   <tag></tag>
   <elementGuidId>3d43b43c-eb85-48fc-805a-e2318347f30a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61c70c90-2266-40af-819b-7ccf2e4b5bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>b2a9514a-9a5d-4b8a-9db5-d8a8a53506ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4212b020-0998-4df5-8bd3-09ac253b3ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Captcha Above</value>
      <webElementGuid>c2470e05-aaa5-4616-9763-e05c14c26419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>d465a5ae-57f1-4503-add9-1a3d51d07ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ec-neutral-500 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6f8c5b86-03d0-475c-bf95-c535c684c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaAnswer&quot;)</value>
      <webElementGuid>0a77924e-6f3b-4052-820a-72a86cecf043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaAnswer']</value>
      <webElementGuid>48b175a0-a849-4cad-8e02-8ee9f529abfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/div[3]/form/div[8]/div/div/input</value>
      <webElementGuid>5929ae3d-4930-48a4-8de8-b078953052d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>68be1990-b8ca-497c-998e-dfd387954bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captchaAnswer' and @type = 'text' and @placeholder = 'Insert Captcha Above']</value>
      <webElementGuid>c40c5a07-4c9c-49a1-8356-3c7f516df39d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
