<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up with google</name>
   <tag></tag>
   <elementGuidId>1095dd05-4d08-41d5-bb68-24b694683928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ec-btn.w-100.login-google.ec-btn-rounded.d-flex.align-items-center.gap-2.justify-content-center.pt-2.ec-neutral-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home-banner']/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e167c98-d180-495b-8a1c-b739059ac974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-btn w-100 login-google ec-btn-rounded d-flex align-items-center gap-2 justify-content-center pt-2 ec-neutral-50</value>
      <webElementGuid>cf999b33-6c8e-4980-a446-65d89edc52ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign up with google </value>
      <webElementGuid>7ed204c9-5b7d-4c11-ae86-d5b59b04ccb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-banner&quot;)/div[@class=&quot;ec-row&quot;]/div[@class=&quot;ec-col-12 ec-col-md-4 d-flex&quot;]/div[@class=&quot;ec-row&quot;]/div[@class=&quot;ec-col-12 d-flex flex-column justify-content-end&quot;]/button[@class=&quot;ec-btn w-100 login-google ec-btn-rounded d-flex align-items-center gap-2 justify-content-center pt-2 ec-neutral-50&quot;]</value>
      <webElementGuid>5c687177-d4f2-47e2-802f-e6004630b896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home-banner']/div/div[2]/div/div/button</value>
      <webElementGuid>87ba8f75-ec78-49ce-97f5-546bd3df18bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::button[1]</value>
      <webElementGuid>2c3b5acb-5679-4691-8b8e-549361151c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[1]</value>
      <webElementGuid>3c37334f-2150-4ef1-936c-1690393b6289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up with google']/parent::*</value>
      <webElementGuid>541b7f3f-9c3a-4b62-a6be-0ce8a0775973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>70a3ff1f-78a2-45e1-b22b-5b3e804586aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Sign up with google ' or . = ' Sign up with google ')]</value>
      <webElementGuid>e06c5fd7-9f7c-4f0e-a24f-37a4e9d41e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
