<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Log InPlease enter your details Don_05e434</name>
   <tag></tag>
   <elementGuidId>32bac538-06ee-468a-8eef-83e71eb310e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home-banner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>7dc13b7b-c5d6-41cd-857b-d289e76a343f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-banner</value>
      <webElementGuid>64a43d45-faed-46ba-9f77-61359a379fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log InPlease enter your details Don’t have account? Create an accountEmailPasswordForgot Password Login or Sign up with google </value>
      <webElementGuid>55bab47e-1ed2-4a69-9cfc-0c14f8785137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-banner&quot;)</value>
      <webElementGuid>7ab7e492-0a31-49f0-9948-6b70de9f6512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='home-banner']</value>
      <webElementGuid>9cf37d8b-14e5-492d-9cec-b25b3003551a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>c131c4b4-e339-4c7e-bede-464d761e16ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'home-banner' and (text() = 'Log InPlease enter your details Don’t have account? Create an accountEmailPasswordForgot Password Login or Sign up with google ' or . = 'Log InPlease enter your details Don’t have account? Create an accountEmailPasswordForgot Password Login or Sign up with google ')]</value>
      <webElementGuid>586ec513-908d-4267-b903-2e711402b4a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
